In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

# Validación
from sklearn.model_selection import KFold


# Metricas
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
df  = pd.read_csv("../data/water_potability_10.csv")
df.head()

ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0  8.661592  284.098352  27088.476460     7.897857  322.146710    512.277310   
1  7.558076  253.840904  16642.884178    11.224395  344.099289    555.932991   
2  5.622807  194.463239  16119.340190     6.907987  336.648207    408.459081   
3  5.045626  179.702503  22557.603596    10.120334  296.425154    450.295696   
4  7.709106  178.810828  18610.124152     7.734441  358.635733    462.201163   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       16.912142        72.465763   3.670431         0.0  
1       15.154628        81.746095   4.169005         0.0  
2       16.364724        76.631186   3.992957         0.0  
3       14.215817        82.066334   3.331787         0.0  
4       13.888704        64.841637   4.235108         0.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ph               164 non-null    float64
 1   Hardness         164 non-null    float64
 2   Solids           164 non-null    float64
 3   Chloramines      164 non-null    float64
 4   Sulfate          164 non-null    float64
 5   Conductivity     164 non-null    float64
 6   Organic_carbon   164 non-null    float64
 7   Trihalomethanes  164 non-null    float64
 8   Turbidity        164 non-null    float64
 9   Potability       164 non-null    float64
dtypes: float64(10)
memory usage: 12.9 KB


In [4]:
df["Potability"].value_counts()

0.0    100
1.0     64
Name: Potability, dtype: int64

In [5]:
X = df.drop("Potability",axis=1)
y = df["Potability"].values

In [6]:
scaler = pickle.load(open("scaler.pkl", 'rb'))
X = scaler.transform(X)

In [9]:
modelo = pickle.load(open("modelo_entrenado.pkl", 'rb'))

In [10]:
df.iloc[0]

ph                     8.661592
Hardness             284.098352
Solids             27088.476460
Chloramines            7.897857
Sulfate              322.146710
Conductivity         512.277310
Organic_carbon        16.912142
Trihalomethanes       72.465763
Turbidity              3.670431
Potability             0.000000
Name: 0, dtype: float64

In [17]:
X[0]

array([6.12386480e-01, 8.58444756e-01, 6.11189217e+03, 5.90673700e-01,
       5.48664482e-01, 5.78453139e-01, 5.63683585e-01, 5.81913021e-01,
       4.19820573e-01])

In [11]:
modelo.predict(X[0].reshape(1,-1))

array([1.])

In [12]:
y[0]

0.0

In [13]:
df.iloc[2]

ph                     5.622807
Hardness             194.463239
Solids             16119.340190
Chloramines            6.907987
Sulfate              336.648207
Conductivity         408.459081
Organic_carbon        16.364724
Trihalomethanes       76.631186
Turbidity              3.992957
Potability             0.000000
Name: 2, dtype: float64

In [14]:
datos = []
for i in df.columns[:-1]:
    x = input("ingresa el valor de {}".format(i))
    datos.append(float(x))

ingresa el valor de ph 5.62
ingresa el valor de Hardness 194.46
ingresa el valor de Solids 16119.34
ingresa el valor de Chloramines 6.9
ingresa el valor de Sulfate 336.64
ingresa el valor de Conductivity 408.45
ingresa el valor de Organic_carbon 16.36
ingresa el valor de Trihalomethanes 76.39
ingresa el valor de Turbidity 3.99


In [15]:
datos

[5.62, 194.46, 16119.34, 6.9, 336.64, 408.45, 16.36, 76.39, 3.99]

In [16]:
datos = np.array(datos).reshape(1,-1)
datos

array([[5.620000e+00, 1.944600e+02, 1.611934e+04, 6.900000e+00,
        3.366400e+02, 4.084500e+02, 1.636000e+01, 7.639000e+01,
        3.990000e+00]])

In [17]:
datos = scaler.transform(datos)
datos

array([[3.91541157e-01, 5.33305283e-01, 3.63635626e+03, 5.12563601e-01,
        5.89835017e-01, 3.96892065e-01, 5.42528736e-01, 6.13749574e-01,
        4.80242012e-01]])

In [18]:
modelo.predict(datos)

array([0.])

In [19]:
y[2]

0.0