In [1]:
import numpy as np

In [2]:
# np version
np.__version__

'1.26.4'

In [3]:
np.array([1,2,3])


array([1, 2, 3])

In [4]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [5]:
type([1,2,3])

list

In [6]:
vector = np.array([1,2,3,4,5])
vector

array([1, 2, 3, 4, 5])

In [7]:
len(vector)

5

array two dimensions

In [8]:
multi_array = np.array([[1,2,3,4],[4,3,2,1]])
multi_array

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [9]:
multi_array.ndim # give us the dimensions of multi array

2

In [10]:
multi_array.dtype

dtype('int32')

In [ ]:
# flatten, using this for depp learning 
